using MarsReferral.Core;
var passed = 0;
void Test(string name, Action test) { try { test(); passed++; Console.WriteLine("PASS " + name); } catch(Exception ex) { Console.Error.WriteLine("FAIL " + name + ": " + ex.Message); Environment.Exit(1); } }
void Check(bool value, string message = "Assertion failed") { if(!value) throw new Exception(message); }
void Reject(Action action, string contains) { try { action(); } catch(RuleException e) { Check(e.Message.Contains(contains,StringComparison.OrdinalIgnoreCase),e.Message); return; } throw new Exception("Expected validation error"); }
var ops = new Actor(IsOperations:true);
ReferralService Fresh() => new();
(Customer owner, Customer friend) Pair(ReferralService s) { var a=s.Register("Owner One","owner@example.com",null);var b=s.Register("Friend One","friend@example.com",a.Code);return(a,b); }
int Fund(ReferralService s,int customer) { var a=s.CreateApplication(ops,customer,"Home purchase",200000); s.Transition(ops,a.Id,ApplicationStage.Approved);s.Transition(ops,a.Id,ApplicationStage.Funded);return a.Id; }
Test("Empty service never inserts default records",()=>{var d=new ReferralService().Read();Check(d.Customers.Length==0 && d.Applications.Length==0 && d.Rewards.Length==0 && d.Messages.Length==0 && d.Audit.Length==0);});
Test("Registration normalizes and validates email",()=>{var s=Fresh();s.Register(" Owner ","OWNER@EXAMPLE.COM ",null);Reject(()=>s.Register("Other","owner@example.com",null),"already");Reject(()=>s.Register("Other","bad",null),"email");Reject(()=>s.Register(" ","good@example.com",null),"name");});
Test("Invalid signup code is atomic",()=>{var s=Fresh();Reject(()=>s.Register("Friend","friend@example.com","MISSING"),"does not exist");Check(s.Read().Customers.Length==0);});
Test("One code attaches to many profiles",()=>{var s=Fresh();var(a,b)=Pair(s);s.Register("Second Friend","second@example.com",a.Code);Check(s.Read().Customers.Count(x=>x.ReferrerId==a.Id)==2);});
Test("Existing user without code can attach, ignoring code case and spaces",()=>{var s=Fresh();var a=s.Register("Owner","a@example.com",null);var b=s.Register("Friend","b@example.com",null);s.Attach(new(b.Id),b.Id," "+a.Code.ToLower()+" ");Check(s.Read().Customers.Single(x=>x.Id==b.Id).ReferrerId==a.Id);});
Test("Existing code cannot be reused or replaced",()=>{var s=Fresh();var(a,b)=Pair(s);Reject(()=>s.Attach(new(b.Id),b.Id,a.Code),"already used");});
Test("Self referral rejected",()=>{var s=Fresh();var a=s.Register("Owner","a@example.com",null);Reject(()=>s.Attach(new(a.Id),a.Id,a.Code),"own");});
Test("Paused and malformed codes rejected",()=>{var s=Fresh();var(a,b)=Pair(s);s.ToggleCode(ops,a.Id);Reject(()=>s.Register("Next Friend","next@example.com",a.Code),"paused");Reject(()=>s.Register("Next Friend","next@example.com","!"),"6");Check(s.Read().Customers.Single(x=>x.Id==b.Id).ReferrerId==a.Id);});
Test("Circular relationships rejected",()=>{var s=Fresh();var(a,b)=Pair(s);Reject(()=>s.Attach(new(a.Id),a.Id,b.Code),"circular");});
Test("Customer cannot change another profile or create its application",()=>{var s=Fresh();var(a,b)=Pair(s);Reject(()=>s.Attach(new(a.Id),b.Id,a.Code),"another");Reject(()=>s.CreateApplication(new(a.Id),b.Id,"Refinance",2000),"another");});
Test("Amounts, purpose and missing IDs validated",()=>{var s=Fresh();var(a,b)=Pair(s);foreach(var n in new[]{-1m,999m,10000001m,1000.001m})Reject(()=>s.CreateApplication(new(b.Id),b.Id,"Refinance",n),"Amount");Reject(()=>s.CreateApplication(new(b.Id),b.Id,"Unknown",2000),"purpose");Reject(()=>s.CreateApplication(ops,999,"Refinance",2000),"not found");});
Test("Customer cannot advance funding or operate rewards",()=>{var s=Fresh();var(a,b)=Pair(s);var id=s.CreateApplication(new(b.Id),b.Id,"Refinance",2000).Id;Reject(()=>s.Transition(new(b.Id),id,ApplicationStage.Approved),"operations");Reject(()=>s.Review(new(b.Id),1,true,""),"operations");Reject(()=>s.Pay(new(b.Id),1,"TEST",true),"operations");Reject(()=>s.ToggleCode(new(b.Id),b.Id),"operations");});
Test("Cannot skip approval or process unknown application",()=>{var s=Fresh();var(a,b)=Pair(s);var id=s.CreateApplication(ops,b.Id,"Refinance",2000).Id;Reject(()=>s.Transition(ops,id,ApplicationStage.Funded),"transition");Reject(()=>s.Transition(ops,999,ApplicationStage.Approved),"not found");});
Test("Cancellation is terminal and creates no rewards",()=>{var s=Fresh();var(a,b)=Pair(s);var id=s.CreateApplication(ops,b.Id,"Refinance",2000).Id;s.Transition(ops,id,ApplicationStage.Cancelled);Reject(()=>s.Transition(ops,id,ApplicationStage.Approved),"transition");Check(s.Read().Rewards.Length==0);});
Test("Funding creates two exact benefits and one invitation",()=>{var s=Fresh();var(a,b)=Pair(s);Fund(s,b.Id);var d=s.Read();Check(d.Rewards.Length==2);Check(d.Rewards.Single(x=>x.BeneficiaryId==b.Id).Amount==25);Check(d.Rewards.Single(x=>x.BeneficiaryId==a.Id).Amount==50);Check(d.Messages.Count(x=>x.Title=="Your funding is complete")==1);});
Test("Repeated funding is rejected and subsequent applications do not duplicate rewards",()=>{var s=Fresh();var(a,b)=Pair(s);var id=Fund(s,b.Id);Reject(()=>s.Transition(ops,id,ApplicationStage.Funded),"transition");Fund(s,b.Id);Check(s.Read().Rewards.Length==2);Check(s.Read().Messages.Count(x=>x.Title=="Your funding is complete")==1);});
Test("No retroactive reward; next funding after attachment can qualify",()=>{var s=Fresh();var a=s.Register("Owner","a@example.com",null);var b=s.Register("Friend","b@example.com",null);Fund(s,b.Id);s.Attach(new(b.Id),b.Id,a.Code);Check(s.Read().Rewards.Length==0);Fund(s,b.Id);Check(s.Read().Rewards.Length==2);});
Test("Pending reward cannot be paid",()=>{var s=Fresh();var(a,b)=Pair(s);Fund(s,b.Id);Reject(()=>s.Pay(ops,s.Read().Rewards[0].Id,"PAY-1",true),"Approve");});
Test("Rejection requires reason and cannot be paid",()=>{var s=Fresh();var(a,b)=Pair(s);Fund(s,b.Id);var id=s.Read().Rewards[0].Id;Reject(()=>s.Review(ops,id,false,""),"reason");s.Review(ops,id,false,"Not eligible");Reject(()=>s.Pay(ops,id,"PAY-1",true),"Approve");});
Test("Failure remains unpaid, retry pays once, duplicate payment rejected",()=>{var s=Fresh();var(a,b)=Pair(s);Fund(s,b.Id);var id=s.Read().Rewards[0].Id;s.Review(ops,id,true,"");s.Pay(ops,id,"PAY-1",false);Check(s.Read().Rewards[0].Stage==RewardStage.Failed);s.Pay(ops,id,"PAY-1",true);Check(s.Read().Rewards[0].Stage==RewardStage.Paid);Reject(()=>s.Pay(ops,id,"PAY-1",true),"cannot");});
Test("Invalid or reused payment references blocked",()=>{var s=Fresh();var(a,b)=Pair(s);Fund(s,b.Id);foreach(var r in s.Read().Rewards)s.Review(ops,r.Id,true,"");var rr=s.Read().Rewards;Reject(()=>s.Pay(ops,rr[0].Id,"x",true),"reference");s.Pay(ops,rr[0].Id,"PAY-1",true);Reject(()=>s.Pay(ops,rr[1].Id,"pay-1",true),"already");});
Test("Concurrent funding generates one reward pair",()=>{var s=Fresh();var(a,b)=Pair(s);var ids=Enumerable.Range(0,12).Select(_=>s.CreateApplication(ops,b.Id,"Refinance",2000).Id).ToArray();foreach(var id in ids)s.Transition(ops,id,ApplicationStage.Approved);Parallel.ForEach(ids,id=>s.Transition(ops,id,ApplicationStage.Funded));Check(s.Read().Rewards.Length==2);Check(s.Read().Messages.Count(x=>x.Title=="Your funding is complete")==1);});
Test("Concurrent attachment allows exactly one winner",()=>{var s=Fresh();var a=s.Register("Owner A","a@example.com",null);var b=s.Register("Owner B","b@example.com",null);var c=s.Register("Friend","c@example.com",null);var wins=0;Parallel.ForEach(new[]{a.Code,b.Code},code=>{try{s.Attach(new(c.Id),c.Id,code);Interlocked.Increment(ref wins);}catch(RuleException){}});Check(wins==1);});
Test("Snapshot arrays cannot mutate stored records",()=>{var s=Fresh();var(a,b)=Pair(s);var d=s.Read();d.Customers[0]=a with {Name="Changed"};Check(s.Read().Customers[0].Name=="Owner One");});
Test("Onboarding must finish before application creation",()=>{var s=Fresh();var c=s.Register("New Customer","new@example.com",null,onboardingRequired:true);Check(!c.OnboardingComplete);Reject(()=>s.CreateApplication(new(c.Id),c.Id,"Refinance",2000),"onboarding");Reject(()=>s.CompleteOnboarding(new(c.Id),c.Id,false),"Confirm");s.CompleteOnboarding(new(c.Id),c.Id,true);Check(s.Read().Customers.Single().OnboardingComplete);s.CreateApplication(new(c.Id),c.Id,"Refinance",2000);});
Test("Onboarding cannot be completed for another customer or repeated",()=>{var s=Fresh();var a=s.Register("Customer A","a@example.com",null,onboardingRequired:true);var b=s.Register("Customer B","b@example.com",null,onboardingRequired:true);Reject(()=>s.CompleteOnboarding(new(a.Id),b.Id,true),"another");s.CompleteOnboarding(new(a.Id),a.Id,true);Reject(()=>s.CompleteOnboarding(new(a.Id),a.Id,true),"already");});
Test("Admin can approve a lower amount and funding preserves it",()=>{var s=Fresh();var(a,b)=Pair(s);var app=s.CreateApplication(ops,b.Id,"Refinance",200000);s.ApproveAmount(ops,app.Id,180000);var saved=s.Read().Applications.Single();Check(saved.Amount==200000&&saved.ApprovedAmount==180000&&saved.Stage==ApplicationStage.Approved);s.Transition(ops,app.Id,ApplicationStage.Funded);Check(s.Read().Applications.Single().ApprovedAmount==180000);});
Test("Approval amount range, decimals and duplicate approval validated",()=>{var s=Fresh();var(a,b)=Pair(s);var app=s.CreateApplication(ops,b.Id,"Refinance",200000);foreach(var amount in new[]{999m,200001m,1000.001m})Reject(()=>s.ApproveAmount(ops,app.Id,amount),"Approved amount");Reject(()=>s.ApproveAmount(new(b.Id),app.Id,100000),"operations");s.ApproveAmount(ops,app.Id,100000);Reject(()=>s.ApproveAmount(ops,app.Id,100000),"transition");});
Test("Shadow session events require admin and attribute customer actions",()=>{var s=Fresh();var(a,b)=Pair(s);Reject(()=>s.RecordShadow(new(a.Id),b.Id,true),"operations");s.RecordShadow(ops,b.Id,true);s.CreateApplication(new(b.Id,IsShadow:true),b.Id,"Refinance",2000);s.RecordShadow(ops,b.Id,false);var d=s.Read();Check(d.Audit.Any(x=>x.Actor.Contains("Admin shadow")&&x.Action=="Application submitted"));Check(d.Audit.Count(x=>x.Action.StartsWith("Customer shadow"))==2);});
Test("Admin can shadow an onboarding customer but cannot bypass onboarding",()=>{var s=Fresh();var c=s.Register("Pending Customer","pending@example.com",null,onboardingRequired:true);s.RecordShadow(ops,c.Id,true);Reject(()=>s.CreateApplication(new(c.Id,IsShadow:true),c.Id,"Refinance",2000),"onboarding");});
Test("Direct referral creates a ready account with phone and no early reward",()=>{var s=Fresh();var a=s.Register("Owner One","owner@example.com",null);var b=s.Refer(new(a.Id),"Friend One","friend@example.com","+1 416 555 0123");Check(b.ReferrerId==a.Id && b.OnboardingComplete && b.Phone=="+1 416 555 0123");Check(s.Read().Rewards.Length==0);Fund(s,b.Id);Check(s.Read().Rewards.Length==2);});
Test("Direct referral validation is atomic and preserves existing relationships",()=>{var s=Fresh();var(a,b)=Pair(s);var before=s.Read().Customers.Length;Reject(()=>s.Refer(new(a.Id),"New Friend","new@example.com","abc"),"phone");Reject(()=>s.Refer(new(a.Id),"New Friend",b.Email.ToUpper(),"4165550123"),"already");Reject(()=>s.Refer(ops,"New Friend","new@example.com","4165550123"),"Sign in");s.ToggleCode(ops,a.Id);Reject(()=>s.Refer(new(a.Id),"New Friend","new@example.com","4165550123"),"paused");Check(s.Read().Customers.Length==before && s.Read().Customers.Single(x=>x.Id==b.Id).ReferrerId==a.Id);});
Test("Concurrent direct referrals create only one account per email",()=>{var s=Fresh();var a=s.Register("Owner One","owner@example.com",null);var wins=0;Parallel.For(0,8,_=>{try{s.Refer(new(a.Id),"Friend One","friend@example.com","4165550123");Interlocked.Increment(ref wins);}catch(RuleException){}});Check(wins==1);});
Console.WriteLine($"\n{passed} business-rule tests passed.");

PersistenceTests.Run();

SharingTests.Run();

EnquiryRegistrationTests.Run();
